### ISSUE TITLE
Getting an error when generating feed 

### ISSUE THREAD

**Issue by vrkansagara** [weierophinney/mwop.net#5]
`php mwop.net.php feed-generator` 
will throw an error in local development as bellow....

`PHP Warning:  DOMDocument::loadXML(): Entity 'mdash' not defined in Entity, line: 11 in /home/vallabh/git/mwop.net/vendor/zendframework/zend-feed/src/Writer/Renderer/Entry/Atom.php on line 383
PHP Catchable fatal error:  Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given, called in /home/vallabh/git/mwop.net/vendor/zendframework/zend-feed/src/Writer/Renderer/Entry/Atom.php on line 53 and defined in /home/vallabh/git/mwop.net/vendor/zendframework/zend-feed/src/Writer/Renderer/Entry/Atom.php on line 351
`

I have also tried 
`php mwop.net.php feed-generator --outputDir=data/feeds --baseUri=http://mwop.git.local/blog`

and also hacked into `mwop.net.php`  but there is no luck each time having same error as mentioned.

can you look into this issue. Thanks.

**Comment by weierophinney** [comment]
@vrkansagara First, why is this important *to you*, exactly? It's *my* site. Are you republishing somewhere? ;-)

Second, I cannot reproduce. Your error indicates that DOMDocument is having trouble parsing `&mdash;` as an HTML entity. What's bizarre is that it's a perfectly valid HTML entity; I'm wondering if the issue is a bad or outdated version of libxml in your PHP installation, or potentially an encoding issue. You can search and replace in `data/posts/` for the entity, and replace it with `&#8212;` to see if that makes a difference.

**Comment by vrkansagara** [comment]
@weierophinney  I am not republishing :-) . I am reading your web blog every day and learning your coding patter and suddenly I found something unusual so I have reported.  

your code behind the mwop.net is inspired me to write more clean and documented code.

Thanks a lot . for mwop.net code.
